name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths: [ 'docker/python-selenium-chrome/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./docker/python-selenium-chrome
        file: ./docker/python-selenium-chrome/Dockerfile
        push: true
        tags: |
          ghcr.io/carloz2er/pterodactyl:python-selenium-chrome
          ghcr.io/carloz2er/pterodactyl:python-selenium-chrome-latest
